// App Store
export const DECREMENT_LOADING = 'DECREMENT_LOADING'
export const INCREMENT_LOADING = 'INCREMENT_LOADING'

// Consumer Store
export const SET_CONSUMER_LIST = 'SET_CONSUMER_LIST'
export const SET_CONSUMER_TYPES = 'SET_CONSUMER_TYPES'
export const DELETE_CONSUMER = 'DELETE_CONSUMER'
export const SET_CONSUMER_STATS = 'SET_CONSUMER_STATS'