// App Store
export const DECREMENT_LOADING = 'DECREMENT_LOADING'
export const INCREMENT_LOADING = 'INCREMENT_LOADING'

export const SET_CONSUMER_LIST = 'SET_CONSUMER_LIST'
export const SET_CONSUMER_TYPES = 'SET_CONSUMER_TYPES'